import fs from 'fs'; import dotenv from 'dotenv'; import { createClient } from '@supabase/supabase-js';
const e = dotenv.parse(fs.readFileSync('.env')); const sb = createClient(e.SUPABASE_URL, e.SUPABASE_SERVICE_ROLE_KEY || e.SUPABASE_SERVICE_KEY, { auth: { persistSession: false } });
const all = async (t, cols, f) => { let out = []; for (let i = 0; ; i += 1000) { const { data } = await f(sb.from(t).select(cols)).order('id').range(i, i + 999).throwOnError(); out = out.concat(data); if (data.length < 1000) break; } return out; };
const offers = await all('rental_cat_offers', 'ticket_number, supplier_id, model_id, offer_type, offer_label, contract_months, care_type, care_label, monthly_fee, rebate, guide_payout, price_phases, notes, source', (q) => q.eq('status', 'active').eq('crm_enabled', true));
const models = await all('rental_cat_models', 'id, product_name, model_code, category, image_url, specs', () => sb.from('rental_cat_models').select('id, product_name, model_code, category, image_url, specs'));
const M = new Map(models.map((m) => [m.id, m]));
const out = {};
out.rebate = offers.filter((o) => !(o.rebate > 0)).map((o) => ({ ticket: o.ticket_number, sup: o.supplier_id, sheet: o.source?.sheet, row: o.source?.row, product: M.get(o.model_id)?.product_name, type: o.offer_type, note: (o.notes || '').slice(0, 80) }));
out.half = offers.filter((o) => (o.offer_type === 'half' || /반값/.test(o.offer_label || '')) && !(o.price_phases || []).length).map((o) => ({ ticket: o.ticket_number, sup: o.supplier_id, product: M.get(o.model_id)?.product_name, label: o.offer_label, months: o.contract_months, fee: o.monthly_fee }));
const careCats = ['water-purifier', 'bidet', 'air-purifier', 'softener'];
out.care = offers.filter((o) => !o.care_type && !o.care_label && careCats.includes(M.get(o.model_id)?.category)).map((o) => ({ ticket: o.ticket_number, sup: o.supplier_id, product: M.get(o.model_id)?.product_name, code: M.get(o.model_id)?.model_code }));
const sellable = new Set(offers.map((o) => o.model_id));
out.noimg = models.filter((m) => sellable.has(m.id) && !m.image_url).map((m) => ({ code: m.model_code, product: m.product_name, cat: m.category }));
const g = (a, k) => a.reduce((m, x) => ((m[k(x)] = (m[k(x)] || 0) + 1), m), {});
console.log('수수료 없음', out.rebate.length, JSON.stringify(g(out.rebate, (x) => x.sup)));
console.log('  시트·행 예', JSON.stringify(out.rebate.slice(0, 3).map((x) => [x.ticket, x.sheet, x.row, x.type])));
console.log('반값 개월 미확인', out.half.length, JSON.stringify(g(out.half, (x) => x.sup)));
console.log('  상품 예', JSON.stringify([...new Set(out.half.map((x) => x.product))].slice(0, 5)));
console.log('관리방식 미확인', out.care.length, JSON.stringify(g(out.care, (x) => x.sup)), JSON.stringify([...new Set(out.care.map((x) => x.code))]));
console.log('이미지 없음', out.noimg.length, JSON.stringify(g(out.noimg, (x) => x.cat)));
fs.writeFileSync('/private/tmp/claude-501/-Users-vinsenzo/88fff588-4fb8-4c65-8825-95625f74aae7/scratchpad/ask_bilrigo.json', JSON.stringify(out, null, 1));
process.exit(0);
